### ISSUE TITLE
Anki 2.1.20beta6 startup error

### ISSUE THREAD

**Issue by khonkhortisan** [nickdvlpr/Redesign#6]
```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (23f13a31) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 73, in handler
  File "aqt\main.py", line 148, in setupProfileAfterWebviewsLoaded
  File "aqt\main.py", line 185, in setupProfile
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-162>", line 2, in loadProfile
  File "lib\site-packages\anki\hooks.py", line 506, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 501, in repl
  File "aqt\main.py", line 353, in loadProfile
  File "aqt\gui_hooks.py", line 595, in __call__
  File "lib\site-packages\anki\hooks.py", line 451, in runHook
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1914733489\redesign.py", line 156, in load
    self.config.load()
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1914733489\config.py", line 32, in load
    setting.on_load()
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1914733489\actions_and_settings.py", line 371, in on_load
    self.app.on()
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1914733489\redesign.py", line 170, in on
    self.styles.replace()
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1914733489\redesign.py", line 96, in replace
    styler.replace_attributes()
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1914733489\stylers.py", line 71, in replace_attributes
    self.get_or_create_original(key)
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\1914733489\stylers.py", line 57, in get_or_create_original
    original = getattr(self.target, key)
AttributeError: module 'aqt.browser' has no attribute 'COLOUR_MARKED'
```
[info] https://anki.tenderapp.com/discussions/beta-testing/1708-anki-2120-beta

**Comment by nickdvlpr** [comment]
Fixed in latest version (2/29/2020).
